### ISSUE TITLE
Improve scraping

### ISSUE THREAD

**Issue by jdggraaf** [neskk/PoGo-Proxies#1]
Hey Neskk,

Love your work but couldn't find any other way to contact you.
I might have an idea, but I don't know if it's too hard to implement: I have this program which uses google (as well as bing and yahoo) to search for more proxies using tested previous proxies as a search basis. 

Might be an idea to expand the range of possible results.

Thanks for your work,

**Comment by neskk** [comment]
Just saw this post :( That's a neat idea actually never thought of it 👍. Right now I'm not very concerned with the amount of proxies the script can scrap, but I'm adding more features to improve testing. I seem to get some "false positives" and I would love to iron them out. Also I'm thinking about adding a database to keep record of uptimes/bans. Code is a bit messy already it needs some refactoring before it can get more complex.
Thanks for your positive feedback, I've been force-pushing some changes lately, should be back on track now.
